# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the daemon process (increased to 4096m).
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -XX:+UseParallelGC -Dsun.io.useCanonCaches=false

# Full JDK location containing javac and jlink tools
org.gradle.java.home=C:/Program Files/Android/Android Studio1/jbr

# Enable Gradle Build Cache (reuses unchanged task outputs across builds)
org.gradle.caching=true

# Compile independent modules/tasks in parallel
org.gradle.parallel=true

# Keep Gradle daemon alive and enable configuration caching
org.gradle.configuration-cache=true

# Kotlin Daemon JVM arguments & Windows File-Locking Optimizations
kotlin.daemon.jvmargs=-Xmx4096M -XX:+UseParallelGC
kotlin.daemon.client.alive.timeout=60000
kotlin.incremental.useClasspathSnapshot=false
android.disallowKotlinSourceSets=false
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
